name: Build & Push Caddy Image

on:
  push:
    #paths:
    #  - 'build/**'
  workflow_dispatch:

jobs:
  build-caddy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load build config
        run: |
          sed -i 's/\r$//' build/build.env
          source build/build.env

          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "CADDY_VERSION=$CADDY_VERSION" >> $GITHUB_ENV
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      - name: Define image tags
        run: |
          echo "TAG_BUILD=${CADDY_VERSION}-${BUILD}" >> $GITHUB_ENV
          echo "TAG_VERSION=${CADDY_VERSION}" >> $GITHUB_ENV
          echo "TAG_LATEST=latest" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Caddy Image
        uses: docker/build-push-action@v5
        with:
          context: build
          file: build/Dockerfile
          platforms: ${{ env.PLATFORM }}
          push: true
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.TAG_BUILD }}
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}
            ${{ secrets.DOCKERHUB_USER }}/${{ env.IMAGE_NAME }}:latest


